apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"external-secrets.io/v1","kind":"ClusterSecretStore","metadata":{"annotations":{},"name":"aws-secrets-manager"},"spec":{"provider":{"aws":{"region":"eu-central-1","service":"SecretsManager"}}}}
  name: aws-secrets-manager
spec:
  provider:
    aws:
      region: eu-central-1
      service: SecretsManager
status:
  capabilities: ReadWrite
  conditions:
  - lastTransitionTime: "2026-05-06T20:05:31Z"
    message: store validated
    reason: Valid
    status: "True"
    type: Ready
