apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"external-secrets.io/v1","kind":"ExternalSecret","metadata":{"annotations":{},"name":"demo-app-config","namespace":"default"},"spec":{"data":[{"remoteRef":{"key":"aws-platform-demo/demo-app/config","property":"app_env"},"secretKey":"app_env"},{"remoteRef":{"key":"aws-platform-demo/demo-app/config","property":"db_password"},"secretKey":"db_password"},{"remoteRef":{"key":"aws-platform-demo/demo-app/config","property":"api_key"},"secretKey":"api_key"}],"refreshInterval":"1h","secretStoreRef":{"kind":"ClusterSecretStore","name":"aws-secrets-manager"},"target":{"creationPolicy":"Owner","name":"demo-app-config"}}}
  finalizers:
  - externalsecrets.external-secrets.io/externalsecret-cleanup
  name: demo-app-config
  namespace: default
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: aws-platform-demo/demo-app/config
      metadataPolicy: None
      nullBytePolicy: Ignore
      property: app_env
    secretKey: app_env
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: aws-platform-demo/demo-app/config
      metadataPolicy: None
      nullBytePolicy: Ignore
      property: db_password
    secretKey: db_password
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: aws-platform-demo/demo-app/config
      metadataPolicy: None
      nullBytePolicy: Ignore
      property: api_key
    secretKey: api_key
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: demo-app-config
status:
  binding:
    name: demo-app-config
  conditions:
  - lastTransitionTime: "2026-05-06T20:05:35Z"
    message: secret synced
    reason: SecretSynced
    status: "True"
    type: Ready
  refreshTime: "2026-05-06T20:05:35Z"
  syncedResourceVersion: 1-dfdca58d0eda3aef2b188841288a7528d78189e394857469c99ec750
